/**
 *   https://noobnotes.net/the-wheels-on-the-bus-traditional/
 * 
 */

const songs = [
    {
        name: "Boci boci tarka",
        key: "Digit8",
        symbol: "8",
        button: "song1",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 30 },
                { event: "pressed", idx: 2, timestamp: 60 },
                { event: "released", idx: 2, timestamp: 90 },
                { event: "pressed", idx: 0, timestamp: 120 },
                { event: "released", idx: 0, timestamp: 150 },
                { event: "pressed", idx: 2, timestamp: 180 },
                { event: "released", idx: 2, timestamp: 210 },
                { event: "pressed", idx: 4, timestamp: 240 },
                { event: "released", idx: 4, timestamp: 300 },
                { event: "pressed", idx: 4, timestamp: 360 },
                { event: "released", idx: 4, timestamp: 420 },
                { event: "pressed", idx: 0, timestamp: 480 },
                { event: "released", idx: 0, timestamp: 510 },
                { event: "pressed", idx: 2, timestamp: 540 },
                { event: "released", idx: 2, timestamp: 570 },
                { event: "pressed", idx: 0, timestamp: 600 },
                { event: "released", idx: 0, timestamp: 630 },
                { event: "pressed", idx: 2, timestamp: 660 },
                { event: "released", idx: 2, timestamp: 690 },
                { event: "pressed", idx: 4, timestamp: 720 },
                { event: "released", idx: 4, timestamp: 780 },
                { event: "pressed", idx: 4, timestamp: 840 },
                { event: "released", idx: 4, timestamp: 900 },
                { event: "pressed", idx: 12, timestamp: 960 },
                { event: "released", idx: 12, timestamp: 990 },
                { event: "pressed", idx: 6, timestamp: 1020 },
                { event: "released", idx: 6, timestamp: 1050 },
                { event: "pressed", idx: 5, timestamp: 1080 },
                { event: "released", idx: 5, timestamp: 1110 },
                { event: "pressed", idx: 4, timestamp: 1140 },
                { event: "released", idx: 4, timestamp: 1170 },
                { event: "pressed", idx: 3, timestamp: 1200 },
                { event: "released", idx: 3, timestamp: 1260 },
                { event: "pressed", idx: 5, timestamp: 1320 },
                { event: "released", idx: 5, timestamp: 1380 },
                { event: "pressed", idx: 4, timestamp: 1440 },
                { event: "released", idx: 4, timestamp: 1470 },
                { event: "pressed", idx: 3, timestamp: 1500 },
                { event: "released", idx: 3, timestamp: 1530 },
                { event: "pressed", idx: 2, timestamp: 1560 },
                { event: "released", idx: 2, timestamp: 1590 },
                { event: "pressed", idx: 1, timestamp: 1620 },
                { event: "released", idx: 1, timestamp: 1650 },
                { event: "pressed", idx: 0, timestamp: 1680 },
                { event: "released", idx: 0, timestamp: 1740 },
                { event: "pressed", idx: 0, timestamp: 1800 },
                { event: "released", idx: 0, timestamp: 1860 }
            ]
    }, {
        name: "Twinkle little star",
        key: "Digit9",
        symbol: "9",
        button: "song2",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 21 },
                { event: "pressed", idx: 0, timestamp: 46 },
                { event: "released", idx: 0, timestamp: 67 },
                { event: "pressed", idx: 4, timestamp: 93 },
                { event: "released", idx: 4, timestamp: 113 },
                { event: "pressed", idx: 4, timestamp: 136 },
                { event: "released", idx: 4, timestamp: 159 },
                { event: "pressed", idx: 5, timestamp: 184 },
                { event: "released", idx: 5, timestamp: 202 },
                { event: "pressed", idx: 5, timestamp: 229 },
                { event: "released", idx: 5, timestamp: 250 },
                { event: "pressed", idx: 4, timestamp: 275 },
                { event: "released", idx: 4, timestamp: 328 },
                { event: "pressed", idx: 3, timestamp: 424 },
                { event: "released", idx: 3, timestamp: 449 },
                { event: "pressed", idx: 3, timestamp: 466 },
                { event: "released", idx: 3, timestamp: 487 },
                { event: "pressed", idx: 2, timestamp: 513 },
                { event: "released", idx: 2, timestamp: 534 },
                { event: "pressed", idx: 2, timestamp: 559 },
                { event: "released", idx: 2, timestamp: 579 },
                { event: "pressed", idx: 1, timestamp: 608 },
                { event: "released", idx: 1, timestamp: 621 },
                { event: "pressed", idx: 1, timestamp: 652 },
                { event: "released", idx: 1, timestamp: 672 },
                { event: "pressed", idx: 0, timestamp: 700 },
                { event: "released", idx: 0, timestamp: 764 },
                { event: "pressed", idx: 4, timestamp: 804 },
                { event: "released", idx: 4, timestamp: 826 },
                { event: "pressed", idx: 4, timestamp: 848 },
                { event: "released", idx: 4, timestamp: 868 },
                { event: "pressed", idx: 3, timestamp: 897 },
                { event: "released", idx: 3, timestamp: 915 },
                { event: "pressed", idx: 3, timestamp: 943 },
                { event: "released", idx: 3, timestamp: 962 },
                { event: "pressed", idx: 2, timestamp: 993 },
                { event: "released", idx: 2, timestamp: 1009 },
                { event: "pressed", idx: 2, timestamp: 1039 },
                { event: "released", idx: 2, timestamp: 1057 },
                { event: "pressed", idx: 1, timestamp: 1090 },
                { event: "released", idx: 1, timestamp: 1155 },
                { event: "pressed", idx: 4, timestamp: 1187 },
                { event: "released", idx: 4, timestamp: 1211 },
                { event: "pressed", idx: 4, timestamp: 1230 },
                { event: "released", idx: 4, timestamp: 1246 },
                { event: "pressed", idx: 3, timestamp: 1277 },
                { event: "released", idx: 3, timestamp: 1298 },
                { event: "pressed", idx: 3, timestamp: 1320 },
                { event: "released", idx: 3, timestamp: 1339 },
                { event: "pressed", idx: 2, timestamp: 1369 },
                { event: "released", idx: 2, timestamp: 1389 },
                { event: "pressed", idx: 2, timestamp: 1414 },
                { event: "released", idx: 2, timestamp: 1433 },
                { event: "pressed", idx: 1, timestamp: 1464 },
                { event: "released", idx: 1, timestamp: 1514 },
                { event: "pressed", idx: 0, timestamp: 1563 },
                { event: "released", idx: 0, timestamp: 1582 },
                { event: "pressed", idx: 0, timestamp: 1609 },
                { event: "released", idx: 0, timestamp: 1630 },
                { event: "pressed", idx: 4, timestamp: 1656 },
                { event: "released", idx: 4, timestamp: 1678 },
                { event: "pressed", idx: 4, timestamp: 1701 },
                { event: "released", idx: 4, timestamp: 1722 },
                { event: "pressed", idx: 5, timestamp: 1752 },
                { event: "released", idx: 5, timestamp: 1770 },
                { event: "pressed", idx: 5, timestamp: 1800 },
                { event: "released", idx: 5, timestamp: 1818 },
                { event: "pressed", idx: 4, timestamp: 1848 },
                { event: "released", idx: 4, timestamp: 1901 },
                { event: "pressed", idx: 3, timestamp: 1947 },
                { event: "released", idx: 3, timestamp: 1968 },
                { event: "pressed", idx: 3, timestamp: 1990 },
                { event: "released", idx: 3, timestamp: 2012 },
                { event: "pressed", idx: 2, timestamp: 2035 },
                { event: "released", idx: 2, timestamp: 2056 },
                { event: "pressed", idx: 2, timestamp: 2081 },
                { event: "released", idx: 2, timestamp: 2103 },
                { event: "pressed", idx: 1, timestamp: 2128 },
                { event: "released", idx: 1, timestamp: 2151 },
                { event: "pressed", idx: 1, timestamp: 2175 },
                { event: "released", idx: 1, timestamp: 2197 },
                { event: "pressed", idx: 0, timestamp: 2229 },
                { event: "released", idx: 0, timestamp: 2254 }
            ]
    },
    {
        name: "Wheels On The Bus",
        key: "Digit0",
        symbol: "0",
        button: "song3",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 10 },
                { event: "pressed", idx: 3, timestamp: 93 },
                { event: "released", idx: 3, timestamp: 106 },
                { event: "pressed", idx: 3, timestamp: 125 },
                { event: "released", idx: 3, timestamp: 132 },
                { event: "pressed", idx: 3, timestamp: 147 },
                { event: "released", idx: 3, timestamp: 153 },
                { event: "pressed", idx: 3, timestamp: 171 },
                { event: "released", idx: 3, timestamp: 180 },
                { event: "pressed", idx: 5, timestamp: 220 },
                { event: "released", idx: 5, timestamp: 227 },
                { event: "pressed", idx: 12, timestamp: 268 },
                { event: "released", idx: 12, timestamp: 276 },
                { event: "pressed", idx: 5, timestamp: 319 },
                { event: "released", idx: 5, timestamp: 326 },
                { event: "pressed", idx: 3, timestamp: 378 },
                { event: "released", idx: 3, timestamp: 387 },
                { event: "pressed", idx: 4, timestamp: 471 },
                { event: "released", idx: 4, timestamp: 489 },
                { event: "pressed", idx: 2, timestamp: 530 },
                { event: "released", idx: 2, timestamp: 538 },
                { event: "pressed", idx: 0, timestamp: 574 },
                { event: "released", idx: 0, timestamp: 594 },
                { event: "pressed", idx: 5, timestamp: 716 },
                { event: "released", idx: 5, timestamp: 730 },
                { event: "pressed", idx: 4, timestamp: 760 },
                { event: "released", idx: 4, timestamp: 770 },
                { event: "pressed", idx: 3, timestamp: 804 },
                { event: "released", idx: 3, timestamp: 815 },
                { event: "pressed", idx: 0, timestamp: 931 },
                { event: "released", idx: 0, timestamp: 942 },
                { event: "pressed", idx: 3, timestamp: 985 },
                { event: "released", idx: 3, timestamp: 998 },
                { event: "pressed", idx: 3, timestamp: 1023 },
                { event: "released", idx: 3, timestamp: 1035 },
                { event: "pressed", idx: 3, timestamp: 1048 },
                { event: "released", idx: 3, timestamp: 1054 },
                { event: "pressed", idx: 3, timestamp: 1077 },
                { event: "released", idx: 3, timestamp: 1086 },
                { event: "pressed", idx: 5, timestamp: 1137 },
                { event: "released", idx: 5, timestamp: 1146 },
                { event: "pressed", idx: 12, timestamp: 1195 },
                { event: "released", idx: 12, timestamp: 1209 },
                { event: "pressed", idx: 5, timestamp: 1287 },
                { event: "released", idx: 5, timestamp: 1302 },
                { event: "pressed", idx: 3, timestamp: 1346 },
                { event: "released", idx: 3, timestamp: 1357 },
                { event: "pressed", idx: 4, timestamp: 1464 },
                { event: "released", idx: 4, timestamp: 1482 },
                { event: "pressed", idx: 0, timestamp: 1555 },
                { event: "released", idx: 0, timestamp: 1567 },
                { event: "pressed", idx: 0, timestamp: 1586 },
                { event: "released", idx: 0, timestamp: 1595 },
                { event: "pressed", idx: 3, timestamp: 1631 },
                { event: "released", idx: 3, timestamp: 1639 }]
    }

    /*
    *   https://pianoletternotes.blogspot.com/2017/10/megalovania-undertale-theme.html
    *
    * */

    , {
        name: "Megalovania",
        key: "Minus",
        symbol: "-",
        button: "song4",
        sequence: [
            { "event": "pressed", "idx": 1, "timestamp": 0 },
            { "event": "released", "idx": 1, "timestamp": 6 },
            { "event": "pressed", "idx": 1, "timestamp": 15 },
            { "event": "released", "idx": 1, "timestamp": 20 },
            { "event": "pressed", "idx": 13, "timestamp": 30 },
            { "event": "released", "idx": 13, "timestamp": 40 },
            { "event": "pressed", "idx": 5, "timestamp": 45 },
            { "event": "released", "idx": 5, "timestamp": 55 },
            { "event": "pressed", "idx": 10, "timestamp": 60 },
            { "event": "released", "idx": 10, "timestamp": 70 },
            { "event": "pressed", "idx": 4, "timestamp": 75 },
            { "event": "released", "idx": 4, "timestamp": 85 },
            { "event": "pressed", "idx": 3, "timestamp": 90 },
            { "event": "released", "idx": 3, "timestamp": 100 },
            { "event": "pressed", "idx": 1, "timestamp": 1068 },
            { "event": "released", "idx": 1, "timestamp": 1076 },
            { "event": "pressed", "idx": 3, "timestamp": 1181 },
            { "event": "released", "idx": 3, "timestamp": 1187 },
            { "event": "pressed", "idx": 4, "timestamp": 1332 },
            { "event": "released", "idx": 4, "timestamp": 1337 },
            { "event": "pressed", "idx": 0, "timestamp": 1667 },
            { "event": "released", "idx": 0, "timestamp": 1674 },
            { "event": "pressed", "idx": 0, "timestamp": 1684 },
            { "event": "released", "idx": 0, "timestamp": 1692 },
            { "event": "pressed", "idx": 13, "timestamp": 1948 },
            { "event": "released", "idx": 13, "timestamp": 1960 },
            { "event": "pressed", "idx": 5, "timestamp": 2127 },
            { "event": "released", "idx": 5, "timestamp": 2135 },
            { "event": "pressed", "idx": 10, "timestamp": 2261 },
            { "event": "released", "idx": 10, "timestamp": 2266 },
            { "event": "pressed", "idx": 4, "timestamp": 2391 },
            { "event": "released", "idx": 4, "timestamp": 2399 },
            { "event": "pressed", "idx": 3, "timestamp": 2574 },
            { "event": "released", "idx": 3, "timestamp": 2583 },
            { "event": "pressed", "idx": 1, "timestamp": 2859 },
            { "event": "released", "idx": 1, "timestamp": 2869 },
            { "event": "pressed", "idx": 3, "timestamp": 2939 },
            { "event": "released", "idx": 3, "timestamp": 2948 },
            { "event": "pressed", "idx": 4, "timestamp": 3092 },
            { "event": "released", "idx": 4, "timestamp": 3103 },
            { "event": "pressed", "idx": 0, "timestamp": 3236 },
            { "event": "released", "idx": 0, "timestamp": 3244 },
            { "event": "pressed", "idx": 0, "timestamp": 3255 },
            { "event": "released", "idx": 0, "timestamp": 3264 },
            { "event": "pressed", "idx": 5, "timestamp": 3512 },
            { "event": "released", "idx": 5, "timestamp": 3522 }]


    },
    /*
    *
    *    https://musescore.com/torbybrand/beginning-minecraft/piano-tutorial
    * 
    */
    {
        name: "Minecraft",
        key: "Equal",
        symbol: "=",
        button: "song5",
        sequence: [
            { "event": "pressed", "idx": 23, "timestamp": 0 },
            { "event": "pressed", "idx": 11, "timestamp": 0 },
            { "event": "released", "idx": 11, "timestamp": 15 },
            { "event": "released", "idx": 23, "timestamp": 15 },
            { "event": "pressed", "idx": 22, "timestamp": 60 },
            { "event": "released", "idx": 22, "timestamp": 75 },
            { "event": "pressed", "idx": 20, "timestamp": 90 },
            { "event": "released", "idx": 20, "timestamp": 105 },
            { "event": "pressed", "idx": 19, "timestamp": 150 },
            { "event": "released", "idx": 19, "timestamp": 165 }
        ]
    }

]