/**
 *   https://noobnotes.net/the-wheels-on-the-bus-traditional/
 * 
 */

const songs = [
    {
        name: "Boci boci tarka",
        key: "Digit1",
        button: "song1",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 20 },
                { event: "pressed", idx: 2, timestamp: 40 },
                { event: "released", idx: 2, timestamp: 60 },
                { event: "pressed", idx: 0, timestamp: 80 },
                { event: "released", idx: 0, timestamp: 100 },
                { event: "pressed", idx: 2, timestamp: 120 },
                { event: "released", idx: 2, timestamp: 140 },
                { event: "pressed", idx: 4, timestamp: 160 },
                { event: "released", idx: 4, timestamp: 200 },
                { event: "pressed", idx: 4, timestamp: 240 },
                { event: "released", idx: 4, timestamp: 280 },
                { event: "pressed", idx: 0, timestamp: 300 },
                { event: "released", idx: 0, timestamp: 320 },
                { event: "pressed", idx: 2, timestamp: 340 },
                { event: "released", idx: 2, timestamp: 360 },
                { event: "pressed", idx: 0, timestamp: 380 },
                { event: "released", idx: 0, timestamp: 400 },
                { event: "pressed", idx: 2, timestamp: 420 },
                { event: "released", idx: 2, timestamp: 440 },
                { event: "pressed", idx: 4, timestamp: 460 },
                { event: "released", idx: 4, timestamp: 500 },
                { event: "pressed", idx: 4, timestamp: 540 },
                { event: "released", idx: 4, timestamp: 580 },
                { event: "pressed", idx: 7, timestamp: 620 },
                { event: "released", idx: 7, timestamp: 640 },
                { event: "pressed", idx: 6, timestamp: 660 },
                { event: "released", idx: 6, timestamp: 680 },
                { event: "pressed", idx: 5, timestamp: 700 },
                { event: "released", idx: 5, timestamp: 720 },
                { event: "pressed", idx: 4, timestamp: 740 },
                { event: "released", idx: 4, timestamp: 760 },
                { event: "pressed", idx: 3, timestamp: 780 },
                { event: "released", idx: 3, timestamp: 820 },
                { event: "pressed", idx: 5, timestamp: 840 },
                { event: "released", idx: 5, timestamp: 880 },
                { event: "pressed", idx: 4, timestamp: 920 },
                { event: "released", idx: 4, timestamp: 940 },
                { event: "pressed", idx: 3, timestamp: 960 },
                { event: "released", idx: 3, timestamp: 980 },
                { event: "pressed", idx: 2, timestamp: 1000 },
                { event: "released", idx: 2, timestamp: 1020 },
                { event: "pressed", idx: 1, timestamp: 1040 },
                { event: "released", idx: 1, timestamp: 1080 },
                { event: "pressed", idx: 0, timestamp: 1100 },
                { event: "released", idx: 0, timestamp: 1140 },
                { event: "pressed", idx: 0, timestamp: 1160 },
                { event: "released", idx: 0, timestamp: 1200 }
            ]
    }, {
        name: "Twinkle little star",
        key: "Digit2",
        button: "song2",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 21 },
                { event: "pressed", idx: 0, timestamp: 46 },
                { event: "released", idx: 0, timestamp: 67 },
                { event: "pressed", idx: 4, timestamp: 93 },
                { event: "released", idx: 4, timestamp: 113 },
                { event: "pressed", idx: 4, timestamp: 136 },
                { event: "released", idx: 4, timestamp: 159 },
                { event: "pressed", idx: 5, timestamp: 184 },
                { event: "released", idx: 5, timestamp: 202 },
                { event: "pressed", idx: 5, timestamp: 229 },
                { event: "released", idx: 5, timestamp: 250 },
                { event: "pressed", idx: 4, timestamp: 275 },
                { event: "released", idx: 4, timestamp: 328 },
                { event: "pressed", idx: 3, timestamp: 424 },
                { event: "released", idx: 3, timestamp: 449 },
                { event: "pressed", idx: 3, timestamp: 466 },
                { event: "released", idx: 3, timestamp: 487 },
                { event: "pressed", idx: 2, timestamp: 513 },
                { event: "released", idx: 2, timestamp: 534 },
                { event: "pressed", idx: 2, timestamp: 559 },
                { event: "released", idx: 2, timestamp: 579 },
                { event: "pressed", idx: 1, timestamp: 608 },
                { event: "released", idx: 1, timestamp: 621 },
                { event: "pressed", idx: 1, timestamp: 652 },
                { event: "released", idx: 1, timestamp: 672 },
                { event: "pressed", idx: 0, timestamp: 700 },
                { event: "released", idx: 0, timestamp: 764 },
                { event: "pressed", idx: 4, timestamp: 804 },
                { event: "released", idx: 4, timestamp: 826 },
                { event: "pressed", idx: 4, timestamp: 848 },
                { event: "released", idx: 4, timestamp: 868 },
                { event: "pressed", idx: 3, timestamp: 897 },
                { event: "released", idx: 3, timestamp: 915 },
                { event: "pressed", idx: 3, timestamp: 943 },
                { event: "released", idx: 3, timestamp: 962 },
                { event: "pressed", idx: 2, timestamp: 993 },
                { event: "released", idx: 2, timestamp: 1009 },
                { event: "pressed", idx: 2, timestamp: 1039 },
                { event: "released", idx: 2, timestamp: 1057 },
                { event: "pressed", idx: 1, timestamp: 1090 },
                { event: "released", idx: 1, timestamp: 1155 },
                { event: "pressed", idx: 4, timestamp: 1187 },
                { event: "released", idx: 4, timestamp: 1211 },
                { event: "pressed", idx: 4, timestamp: 1230 },
                { event: "released", idx: 4, timestamp: 1246 },
                { event: "pressed", idx: 3, timestamp: 1277 },
                { event: "released", idx: 3, timestamp: 1298 },
                { event: "pressed", idx: 3, timestamp: 1320 },
                { event: "released", idx: 3, timestamp: 1339 },
                { event: "pressed", idx: 2, timestamp: 1369 },
                { event: "released", idx: 2, timestamp: 1389 },
                { event: "pressed", idx: 2, timestamp: 1414 },
                { event: "released", idx: 2, timestamp: 1433 },
                { event: "pressed", idx: 1, timestamp: 1464 },
                { event: "released", idx: 1, timestamp: 1514 },
                { event: "pressed", idx: 0, timestamp: 1563 },
                { event: "released", idx: 0, timestamp: 1582 },
                { event: "pressed", idx: 0, timestamp: 1609 },
                { event: "released", idx: 0, timestamp: 1630 },
                { event: "pressed", idx: 4, timestamp: 1656 },
                { event: "released", idx: 4, timestamp: 1678 },
                { event: "pressed", idx: 4, timestamp: 1701 },
                { event: "released", idx: 4, timestamp: 1722 },
                { event: "pressed", idx: 5, timestamp: 1752 },
                { event: "released", idx: 5, timestamp: 1770 },
                { event: "pressed", idx: 5, timestamp: 1800 },
                { event: "released", idx: 5, timestamp: 1818 },
                { event: "pressed", idx: 4, timestamp: 1848 },
                { event: "released", idx: 4, timestamp: 1901 },
                { event: "pressed", idx: 3, timestamp: 1947 },
                { event: "released", idx: 3, timestamp: 1968 },
                { event: "pressed", idx: 3, timestamp: 1990 },
                { event: "released", idx: 3, timestamp: 2012 },
                { event: "pressed", idx: 2, timestamp: 2035 },
                { event: "released", idx: 2, timestamp: 2056 },
                { event: "pressed", idx: 2, timestamp: 2081 },
                { event: "released", idx: 2, timestamp: 2103 },
                { event: "pressed", idx: 1, timestamp: 2128 },
                { event: "released", idx: 1, timestamp: 2151 },
                { event: "pressed", idx: 1, timestamp: 2175 },
                { event: "released", idx: 1, timestamp: 2197 },
                { event: "pressed", idx: 0, timestamp: 2229 },
                { event: "released", idx: 0, timestamp: 2254 }
            ]
    },
    {
        name: "Wheels On The Bus",
        key: "Digit3",
        button: "song3",
        sequence:
            [
                { event: "pressed", idx: 0, timestamp: 0 },
                { event: "released", idx: 0, timestamp: 10 },
                { event: "pressed", idx: 3, timestamp: 93 },
                { event: "released", idx: 3, timestamp: 106 },
                { event: "pressed", idx: 3, timestamp: 125 },
                { event: "released", idx: 3, timestamp: 132 },
                { event: "pressed", idx: 3, timestamp: 147 },
                { event: "released", idx: 3, timestamp: 153 },
                { event: "pressed", idx: 3, timestamp: 171 },
                { event: "released", idx: 3, timestamp: 180 },
                { event: "pressed", idx: 5, timestamp: 220 },
                { event: "released", idx: 5, timestamp: 227 },
                { event: "pressed", idx: 7, timestamp: 268 },
                { event: "released", idx: 7, timestamp: 276 },
                { event: "pressed", idx: 5, timestamp: 319 },
                { event: "released", idx: 5, timestamp: 326 },
                { event: "pressed", idx: 3, timestamp: 378 },
                { event: "released", idx: 3, timestamp: 387 },
                { event: "pressed", idx: 4, timestamp: 471 },
                { event: "released", idx: 4, timestamp: 489 },
                { event: "pressed", idx: 2, timestamp: 530 },
                { event: "released", idx: 2, timestamp: 538 },
                { event: "pressed", idx: 0, timestamp: 574 },
                { event: "released", idx: 0, timestamp: 594 },
                { event: "pressed", idx: 5, timestamp: 716 },
                { event: "released", idx: 5, timestamp: 730 },
                { event: "pressed", idx: 4, timestamp: 760 },
                { event: "released", idx: 4, timestamp: 770 },
                { event: "pressed", idx: 3, timestamp: 804 },
                { event: "released", idx: 3, timestamp: 815 },
                { event: "pressed", idx: 0, timestamp: 931 },
                { event: "released", idx: 0, timestamp: 942 },
                { event: "pressed", idx: 3, timestamp: 985 },
                { event: "released", idx: 3, timestamp: 998 },
                { event: "pressed", idx: 3, timestamp: 1023 },
                { event: "released", idx: 3, timestamp: 1035 },
                { event: "pressed", idx: 3, timestamp: 1048 },
                { event: "released", idx: 3, timestamp: 1054 },
                { event: "pressed", idx: 3, timestamp: 1077 },
                { event: "released", idx: 3, timestamp: 1086 },
                { event: "pressed", idx: 5, timestamp: 1137 },
                { event: "released", idx: 5, timestamp: 1146 },
                { event: "pressed", idx: 7, timestamp: 1195 },
                { event: "released", idx: 7, timestamp: 1209 },
                { event: "pressed", idx: 5, timestamp: 1287 },
                { event: "released", idx: 5, timestamp: 1302 },
                { event: "pressed", idx: 3, timestamp: 1346 },
                { event: "released", idx: 3, timestamp: 1357 },
                { event: "pressed", idx: 4, timestamp: 1464 },
                { event: "released", idx: 4, timestamp: 1482 },
                { event: "pressed", idx: 0, timestamp: 1555 },
                { event: "released", idx: 0, timestamp: 1567 },
                { event: "pressed", idx: 0, timestamp: 1586 },
                { event: "released", idx: 0, timestamp: 1595 },
                { event: "pressed", idx: 3, timestamp: 1631 },
                { event: "released", idx: 3, timestamp: 1639 }]
    }
    , {
        name: "Megalovania",
        key: "Digit4",
        button: "song4",
        sequence: [
            { event: "pressed", idx: 0, timestamp: 0 },
            { event: "released", idx: 0, timestamp: 5 },
            { event: "pressed", idx: 0, timestamp: 24 },
            { event: "released", idx: 0, timestamp: 31 },
            { event: "pressed", idx: 7, timestamp: 66 },
            { event: "released", idx: 7, timestamp: 74 },
            { event: "pressed", idx: 4, timestamp: 120 },
            { event: "released", idx: 4, timestamp: 129 },
            { event: "pressed", idx: 10, timestamp: 193 },
            { event: "released", idx: 10, timestamp: 204 },
            { event: "pressed", idx: 3, timestamp: 238 },
            { event: "released", idx: 3, timestamp: 249 },
            { event: "pressed", idx: 9, timestamp: 279 },
            { event: "released", idx: 9, timestamp: 287 },
            { event: "pressed", idx: 0, timestamp: 317 },
            { event: "released", idx: 0, timestamp: 325 },
            { event: "pressed", idx: 9, timestamp: 389 },
            { event: "released", idx: 9, timestamp: 397 },
            { event: "pressed", idx: 3, timestamp: 438 },
            { event: "released", idx: 3, timestamp: 445 },
            { event: "pressed", idx: 0, timestamp: 473 },
            { event: "released", idx: 0, timestamp: 483 },
            { event: "pressed", idx: 0, timestamp: 499 },
            { event: "released", idx: 0, timestamp: 507 },
            { event: "pressed", idx: 7, timestamp: 545 },
            { event: "released", idx: 7, timestamp: 554 },
            { event: "pressed", idx: 4, timestamp: 608 },
            { event: "released", idx: 4, timestamp: 618 },
            { event: "pressed", idx: 10, timestamp: 689 },
            { event: "released", idx: 10, timestamp: 702 },
            { event: "pressed", idx: 3, timestamp: 732 },
            { event: "released", idx: 3, timestamp: 741 },
            { event: "pressed", idx: 9, timestamp: 776 },
            { event: "released", idx: 9, timestamp: 786 },
            { event: "pressed", idx: 0, timestamp: 835 },
            { event: "released", idx: 0, timestamp: 843 },
            { event: "pressed", idx: 9, timestamp: 865 },
            { event: "released", idx: 9, timestamp: 870 },
            { event: "pressed", idx: 3, timestamp: 899 },
            { event: "released", idx: 3, timestamp: 907 }]
    }


]