levels = {
    value:[
    ' M.MMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM',
    'MMMMMMMMMMMMMMMMMMMM'
    ]
}